### ISSUE TITLE
proxy doesn't work

### ISSUE THREAD

**Issue by frsechet** [RecastAI/SDK-NodeJS#2] opened 2016-10-08 16:02 UTC
This timeouts when behind a corporate proxy.
Also, it should be documented somewhere without having to dig into https://github.com/RecastAI/SDK-NodeJS/blob/master/src/class/client.js#L20 :-)

```
var recastai = require('recastai')

var client = new recastai.Client("xxx", "en")

client.textRequest("where is Robert", { token: "xxx", language: "en", proxy: "http://my.proxy.com:4242" })
  .then(function(res) {
    var intent = res.intent()

    console.log(intent);

  }).catch(function(err) {
    console.log(err);
  })
```

**Comment by jhoudan** [comment] 2016-10-09 08:22
Hi !

Good point, I will improve the documentation for this part.
We are using axios instead of superagent in the version 2.x.x of this SDK, so the proxy parameter has evolved a bit. Now it's an object like the following:
  proxy: {
    host: '127.0.0.1',
    port: 9000
  }
I will update the doc accordingly.

Thanks for reporting this issue !

**Comment by frsechet** [comment] 2016-10-09 08:23
I tried that also, but it still doesn't work. At least with my proxy...

**Comment by jhoudan** [comment] 2016-10-09 08:28
Mmh I will make more tests tomorrow, to see what's going on and if the problem is on our side or on the axios side.
I'll keep you informed of the progress

**Comment by frsechet** [comment] 2016-10-09 08:46
Might be on axios side though, as this also timeouts:
```
var url = 'https://jsonplaceholder.typicode.com/posts';
var axios = require('axios');

axios.get(url)//, {proxy: {host: "http://myproxy.com", port: "4242"}})
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```

May I ask why you switched from superagent to axios? Superagent can be extended with https://www.npmjs.com/package/superagent-promise and https://www.npmjs.com/package/superagent-proxy :-)

**Comment by jhoudan** [comment] 2016-10-21 09:53
We switched from superagent to axios, because we've got some weird errors when we were using webpack to build a project depending on the superagent-proxy module.

I'll have a look on the axios side, and see if we can resolve this issue. If not, we will switch back to superagent!

**Comment by jhoudan** [comment] 2016-11-26 13:32
We've switched back to superagent since a while now, so I close this issue

**Closed by jhoudan** 2016-11-26 13:32 UTC
Labels: hacktoberfest

**Comment by Amit-Kolambikar** [comment] 2016-12-30 10:58
`Failed to compile.

Error in ./~/native-dns-cache/lookup.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns-cache

 @ ./~/native-dns-cache/lookup.js 21:12-28

Error in ./~/get-uri/test/data.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/data.js 8:20-46

Error in ./~/get-uri/test/file.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/file.js 9:20-46

Error in ./~/get-uri/test/ftp.js
Module not found: 'ftpd' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/ftp.js 7:11-26

Error in ./~/get-uri/test/ftp.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/ftp.js 11:20-46

Error in ./~/get-uri/test/http.js
Module not found: 'st' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/http.js 7:9-22

Error in ./~/get-uri/test/http.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/http.js 12:20-46

Error in ./~/get-uri/test/https.js
Module not found: 'st' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/https.js 7:9-22

Error in ./~/get-uri/test/https.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/https.js 12:20-46

Error in ./~/get-uri/test/test.js
Module not found: 'st' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/test.js 7:9-22

Error in ./~/get-uri/test/test.js
Module not found: 'ftpd' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/test.js 8:11-26

Error in ./~/get-uri/test/test.js
Module not found: 'stream-to-array' in /home/amit/Projects/Maverick/node_modules/get-uri/test

 @ ./~/get-uri/test/test.js 13:20-46

Error in ./~/native-dns/lib/server.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns/lib

 @ ./~/native-dns/lib/server.js 23:12-28

Error in ./~/native-dns/lib/utils.js
Module not found: 'dgram' in /home/amit/Projects/Maverick/node_modules/native-dns/lib

 @ ./~/native-dns/lib/utils.js 21:12-28

Error in ./~/defaultable/t/api.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/api.js 17:11-25

Error in ./~/defaultable/t/defaults.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/defaults.js 17:11-25

Error in ./~/defaultable/t/merge.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/merge.js 17:11-25

Error in ./~/defaultable/t/require.js
Module not found: 'tap' in /home/amit/Projects/Maverick/node_modules/defaultable/t

 @ ./~/defaultable/t/require.js 17:11-25
`
I am getting the above error. I think it has something to do with superagent. How should i fix this ?

**Comment by frsechet** [comment] 2016-12-30 19:19
@Amit-Kolambikar you should open a separate issue.
