### ISSUE TITLE
CLIENT.fileRequest fails, same request works with standard http request

### ISSUE THREAD

**Issue by frsechet** [RecastAI/SDK-NodeJS#5] opened 2016-10-23 00:11 UTC
Yop,

This works:

```
  var request = require('superagent');

  request
    .post('https://api.recast.ai/v2/request')
    .attach('voice', file)
    .send({
      language: 'en'
    })
    .set('Authorization', 'Token '+process.env.RECAST_CLIENT)
    .set('Content-Type', '')
    .end(function(err, res) {
      console.log(err, res);
    });
```

This doesn't work with exactly the same file (it returns `Error: Request failed with status code 400` and nothing more, so it's hard to guess what's wrong as it's the same file):

```
var recast = require("recastai");
var CLIENT = new recast.Client(process.env.RECAST_CLIENT, "en");

  CLIENT.fileRequest(file)
    .then(function (data) {
      console.log(data.source);
    })
    .catch(function(err) {
      console.log(err);
    });
```

Here is a file I'm sending. It's in French and I set recast to English but that's not the issue here (it returns 400, not some misunderstood content).
[9cb212b7-067d-4f94-83c0-5f22c4e9cd44.wav.zip](https://github.com/RecastAI/SDK-NodeJS/files/546104/9cb212b7-067d-4f94-83c0-5f22c4e9cd44.wav.zip)

Thanks for having a look! In the meantime, I'll stick with superagent ;-)

**Comment by jhoudan** [comment] 2016-10-24 08:51
Hi Francois,

It's has been fixed in the latest version of the SDK, It should now work as intended!
We switched back to superagent ;-)

Thanks for reporting this issue!

**Closed by jhoudan** 2016-10-24 08:51 UTC
